CREATE TABLE [dbo].[Item]
(
	[ItemId] INT NOT NULL IDENTITY(1,1),
    [ItemName] VARCHAR(250) NOT NULL,
	[InventoryNumber] VARCHAR(10),
	[OldInventoryNumber] VARCHAR(50),
	[SerialNumber] VARCHAR(50),
	[YellowNumber] INT,
	[AccreditationNumber] VARCHAR(50),
	[ProductionYear] DATETIME,
	[BruttoPrice] INT,
	[Manufacturer] VARCHAR(100),
	[ModelType] VARCHAR(100),
	[ItemNatureId] INT NULL,
	[ItemTypeId] INT NULL,
	[DepartmentId] INT,
	[SectionId] INT,
	[BuildingId] INT,
	[FloorId] INT,
	[Room] VARCHAR(100),
	[EmployeeId] INT,
	[ItemStateId] INT,
	[DateOfCreation] DATE,
	[Comment] VARCHAR(2000),
	[DateOfScrap] DATETIME NULL, 
    CONSTRAINT [pkItem] PRIMARY KEY CLUSTERED ([ItemId] ASC),
	CONSTRAINT [fkItemUser] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [fkItemSection] FOREIGN KEY ([SectionId]) REFERENCES [dbo].[Section] ([SectionId]),
	CONSTRAINT [fkItemItemNature] FOREIGN KEY ([ItemNatureId]) REFERENCES [dbo].[ItemNature] ([ItemNatureId]),
	CONSTRAINT [fkItemItemType] FOREIGN KEY ([ItemTypeId]) REFERENCES [dbo].[ItemType] ([ItemTypeId]),
	CONSTRAINT [fkItemDepartment] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([DepartmentId]),
	CONSTRAINT [fkItemItemState] FOREIGN KEY ([ItemStateId]) REFERENCES [dbo].[ItemState] ([ItemStateId]),
	CONSTRAINT [fkItemBuilding] FOREIGN KEY ([BuildingId]) REFERENCES [dbo].[Building] ([BuildingId]),
	CONSTRAINT [fkItemFloor] FOREIGN KEY ([FloorId]) REFERENCES [dbo].[Floor] ([FloorId]),
)