CREATE TABLE [dbo].[Item]
(
	[ItemId] INT NOT NULL IDENTITY(1,1),
    [ItemName] VARCHAR(250) NOT NULL,
	[InventoryNumber] VARCHAR(10),
	--TODO: 50 helyett a karakterkód hossza
	[OldInventoryNumber] VARCHAR(50),
	[SerialNumber] VARCHAR(50),
	[YellowNumber] INT,
	[AccreditaionNumber] VARCHAR(50),
	[ProductionYear] DATETIME,
	[BruttoPrice] INT,
	[Manufacturer] VARCHAR(100),
	[ModelType] VARCHAR(100),
	[ItemNature] INT NULL,
	[ItemType] INT NULL,
	[Department] INT,
	[Section] INT,
	[Building] INT,
	[Floor] INT,
	[Room] INT,
	[Owner] INT,
	[ItemState] INT,
	[DateOfCreation] DATE,
	[Comment] VARCHAR(2000),
	CONSTRAINT [pkItem] PRIMARY KEY CLUSTERED ([ItemId] ASC),
	CONSTRAINT [fkItemUser] FOREIGN KEY ([Owner]) REFERENCES [dbo].[Employee] ([EmployeeId]),
	CONSTRAINT [fkItemSection] FOREIGN KEY ([Section]) REFERENCES [dbo].[Section] ([SectionId]),
	CONSTRAINT [fkItemItemNature] FOREIGN KEY ([ItemNature]) REFERENCES [dbo].[ItemNature] ([ItemNatureId]),
	CONSTRAINT [fkItemItemType] FOREIGN KEY ([ItemType]) REFERENCES [dbo].[ItemType] ([ItemTypeId]),
	CONSTRAINT [fkItemDepartment] FOREIGN KEY ([Department]) REFERENCES [dbo].[Department] ([DepartmentId]),
	CONSTRAINT [fkItemItemState] FOREIGN KEY ([ItemState]) REFERENCES [dbo].[ItemState] ([ItemStateId]),
	CONSTRAINT [fkItemBuilding] FOREIGN KEY ([Building]) REFERENCES [dbo].[Building] ([BuildingId]),
	CONSTRAINT [fkItemFloor] FOREIGN KEY ([Floor]) REFERENCES [dbo].[Floor] ([FloorId]),
)